### ISSUE TITLE
Different tab colors depending on the accelerator section

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#12]
We should implement different tab colors depending on the accelerator section. Blue for SI, green for Bo and so on, like in the UVX. 
This could be implemented using reading <code>QObject.objectName</code> wihtin an <code>siriushla.util function</code>

**Comment by gu1lhermelp** [comment]
@xresende done

**Comment by xresende** [comment]
The  implemented solution seems satisfactory.
