### ISSUE TITLE
[sirius-hla-bo-ma-control] buttons for magnet detail 

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#13]
* they  do not bring child window to front, if window is already open.
same behaviour for other windows.
* is there a way to implement this behaviour in siriushla.util and force all HLA app to use this module thus forcing the same behavior ?

**Comment by gu1lhermelp** [comment]
@xresende create a WindowManager class to handle windows, so that it can be used as general module in all windows

**Comment by xresende** [comment]
see HLA magnet control as as example on how to use <code>WindowManager</code>
