### ISSUE TITLE
not connecting to PVs

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#14]
If the HLA has been initialized and used with an IOC not running, it may take a very long time (> 2 mins) to  connect to the IOC after the IOC is started.

**Comment by fernandohds564** [comment]
Isn't this behavior expected due to epics protocol?

**Comment by xresende** [comment]
I am not sure but I dont think that this connection handshake policy is defined in the CA protocol (http://www.aps.anl.gov/epics/docs/CAproto.html#secCA_PROTO_SEARCH). Tests with both pyepics and 'camonitor' show that connection is established moments after the IOC is brought up. PyDM HLA seem to have a different behaviour...

**Comment by xresende** [comment]
problem persists... sometimes it takes longer than patience allows for checking that connection is established at all!
