### ISSUE TITLE
Establish and close connections of child windows

### ISSUE THREAD

**Issue by anacso17** [lnls-sirius/hla#15]
A new child window in HLA have to establish and close connections intercepting show and close events. 
Suggestion: create a class derivated from QMainWindow that make these treatments. 
Obs: PyDMMainWindow plays a similar role.

**Comment by fernandohds564** [comment]
Done!

**Comment by fernandohds564** [comment]
After thinking more about it, it does not seem to be appropriate to open connections in the `show` method. `SiriusApplication` should always do this. I have done another commit that does that. I also included these classes in QtDesigner.
