### ISSUE TITLE
Widget focus

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#2]
Widget focus is locked to a specify widget even when editing line edit text. 
In hla-tb-ma-control.py, for example, when Current-SP is sent, a Abort-Cmd is issued because its corresponding widget is always focused.

**Comment by gu1lhermelp** [comment]
@xresende done

**Comment by xresende** [comment]
using <code>QMainWindow</code> instead of <code>QDialog</code> solved this issue.
