### ISSUE TITLE
HLA Widgets x PyDM Widgets

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#4]
should we convert HLA widgets into PyDM widgets? if not, the use of the  'designer' will be dropped naturally when most of the widgets are accessed only within HLA. We had decided that we would keep 'designer' as an option, right?

**Comment by fernandohds564** [comment]
I think thats the idea of the SiriusDM package. We can use this package to put widgets that are general enough to be used in several Sirius application windows.
I think of PyDM as a package to put basic building block widgets, for example it is where we put a scrollbar, or a line edit, or even a fancy line edit widget, but it is not the place to put a setpoint-readback current control widget.

Integration of SiriusDM widgets with Designer is trivial and we should do it.

**Comment by xresende** [comment]
I agree with @fernandohds564

**Comment by xresende** [comment]
this has been sorted out in out last meeting about HLA. we will make an effort to incorporate new version of PyDM into our Sirius version and will make an effort to keep our version close to the original PyDM version. using this strategy we should need to implement fewer additional widgets into <code>siriusdm</code>
