### ISSUE TITLE
Child window comes to front in stacking order

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#6]
When child window (TB-01:MA-CH-1, for example) is hidden behind other windows in the system and its parent window (TB Magnet Control Panel) is focused by the user, the child window also comes to front in the stacking order.

Is this the behavior we want ? This might be annoying in some situations. But it can be useful when you want to interact will all children window... (in this case, the bringing to front of all child windows could be triggered with a keyboard shortcut or GUI button....)

**Comment by xresende** [comment]
As @gu1lhermelp explained, this is the default behavior when a 'dialog' child window is opened. It classes can be changed to use another window type.

**Comment by gu1lhermelp** [comment]
@xresende  All windows changed to QMainWindow instead of QDialog

**Comment by xresende** [comment]
tested OK
