### ISSUE TITLE
Kick units within magnet corrector widgets

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#7]
We decided to define differencial units for kicks within the FloatSetPoinWidget class. Its channel can be read to decide for 'mrad' or 'urad', depending on the accelerator section.

**Comment by xresende** [comment]
the dictionary that relates the default kick unit with the accelerator section may be located in <code>siriushla/util.py</code>

**Comment by gu1lhermelp** [comment]
@xresende done

**Comment by xresende** [comment]
@gu1lhermelp kick units for Readback, refMon and Mon in the details window are still in rad, instead of urad and mrad.
