### ISSUE TITLE
[sirius-hla-bo-ma-control] Global Setpoint

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#9]
When using global setpoint in slow correctors (any tab?), two problems:

1. if user hits 'cancel', HLA sends 0.0 to IOC
2. edit line comes with ',' (comma) instead of '.' (period). typing '1.0', for example, sends '10.0' to IOC.

**Comment by gu1lhermelp** [comment]
Done

**Comment by xresende** [comment]
issue 1. tested and it is OK.

**Comment by fernandohds564** [comment]
PyDMSpinbox has the same behavior as 2. I think we need to configure locale correctly.

**Comment by xresende** [comment]
this issue is being discussed in https://github.com/slaclab/pydm/issues/229
